### ISSUE TITLE
Attempted to use a closed Session

### ISSUE THREAD

**Issue by mayidu** [bendidi/Tracking-with-darkflow#17]
Hello, I run the deep sort in py-faster-rcnn, but there are error when use the generate_detections.create_box_encoder get the encoder about "Attempted to use a closed Session", are you get this error, thanks

**Comment by bendidi** [comment]
the error is quite straightforward, you tried to use the session of faster-rcnn after it was closed , so it's either keep the session open (if you loaded deep_sort in same graph as faster-rcnn ) or make a new graph and new session for deep_sort  

Ps : closing the issue because this question is better asked on stack overflow
